language: generic
sudo: required
services: 
    - docker


before_install:
    - docker build -t barnoldcoding/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true barnoldcoding/docker-react npm run test