language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t barnoldcoding/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true barnoldcoding/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-356583478594"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY